<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>AAAplatform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/static/html5shiv/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/bootstrap/img/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/bootstrap/img/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/bootstrap/img/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="/static/bootstrap/img/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/static/bootstrap/img/favicon.png">
  </head>

<?php
  function is_active($check)
  {
    if (!empty($_GET['do']) && eregi ("^$check", $_GET['do']))
    {
      echo "class=\"active\"";
    }
  }

  function my_error ($db)
  {
    switch (mysql_errno($db)) {
      case 1062:
        return 'Entry already exist!';
        break;
      default:
        return mysql_error($db);
    }
  }

  function html_table($table)
  {
    if (empty($table))
    {
      echo "
          <div class=\"hero-unit\">
            <p>No DATA.</p>
          </div>";
    } 
    else 
    {
      echo "
          <table class=\"table table-striped\">
            <thead>
              <tr>";
      foreach (array_keys($table[0]) as $key)
      {
        echo "
                <th>$key</th>";
      }
      echo "
              </tr>
            </thead>
            <tbody>";
      foreach ($table as $line)
      {
        echo "
              <tr>";
        foreach ($line as $cell)
        {
          echo "
                <td>$cell</td>";
        }
        echo "
              </tr>";
      }
      echo "
            </tbody>
          </table>";
    }
  }

  function html_table_control($table, $key, $url, $controls)
  {
    if (empty($table))
    {
      echo "
          <div class=\"hero-unit\">
            <p>No DATA.</p>
          </div>";
    } 
    else 
    {
      echo "
          <table class=\"table table-striped\">
            <thead>
              <tr>";
      foreach (array_keys($table[0]) as $key)
      {
        echo "
                <th>$key</th>";
      }
      echo "
                <th></th>
              </tr>
            </thead>
            <tbody>";
      foreach ($table as $line)
      {
        echo "
              <tr>";
        foreach ($line as $cell)
        {
          echo "
                <td>$cell</td>";
        }
        echo "
                <td>";
        foreach ($controls as $control => $class)
        {
          echo "
                <a href=\"$url/$control\" class=\"btn $class\">$control</a>";
        }
        echo "
                </td>
              </tr>";
      }
      echo "
            </tbody>
          </table>";
    }
  }

  function sql_query($db, $query)
  {
    $result = mysql_query($query) or die('Query failed: ' . mysql_error());
    $table = array();
    while ($line = mysql_fetch_assoc($result)) {
        $table[] = $line;
    }

    // Free resultset
    mysql_free_result($result);

    return $table;
  }

  function write_ini($path, $ini)
  { 
    $content = "
##########################################
# !!! Do NOT edit this file manulay, !!! #
#     it will be rewriten by webapp.     #
##########################################
    "; 

    foreach ($ini as $section => $keyval) {
      $content .= "[$section]\n";
      foreach ($keyval as $key => $values) {
        $content .= "$key =\n";
        foreach ($values as $value) {
          $content .= "    $value\n";
        }
      }
    }

    if (!$handle = fopen($path, 'w')) { 
      return -2; 
    } 
    if (!fwrite($handle, $content)) { 
      return -2; 
    } 
    fclose($handle); 
    return 1; 
  } 

  function parse_ini($path)
  {
    $ini = array();
    $section = '';
    $key = '';
    $lines = file('/etc/tacacs+/do_auth.ini');
    foreach ($lines as $line) {
      $line = preg_replace('/[;#].*/' , '' , $line);
      if (preg_match('/^[[:space:]]*$/', $line) == 0) {
        if (preg_match('/^\s*\[(.*)\]\s*$/', $line, $m) == 1) {
          $section = $m[1];
          $ini[$section] = array();
          continue;
        }
        if (!empty($section)) {
          if (preg_match('/^([a-z0-9_.\[\]-]+)\s*[=]\s*(.*)\s*$/', $line, $m) == 1) {
            $key = $m[1];
            if (!empty($m[2])) {
              $ini[$section][$key][] = $m[2];
            } else {
              $ini[$section][$key] = array();
            }
          } elseif (preg_match('/^\s*(.*)\s*$/', $line, $m) == 1) {
            $ini[$section][$key][] = $m[1];
          }
        }
      }
    }
    return $ini;
  }
?>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">AAAplatform</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <a href="/adminer" class="navbar-link">DB admin</a> | Server IP: <a href="/network" class="navbar-link"><?php echo $_SERVER['SERVER_ADDR'] ?></a>
            </p>
            <ul class="nav">
              <li <?php is_active('radius') ?> ><a href="/radius">RADIUS</a></li>
              <li <?php is_active('tacacs') ?> ><a href="/tacacs">TACACS+</a></li>
              <li <?php is_active('diameter') ?> ><a href="/diameter">Diameter</a></li>
              <li <?php is_active('kerberos') ?> ><a href="/kerberos">KERBEROS</a></li>
              <li <?php is_active('syslog') ?> ><a href="/syslog">Syslog</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">

<?php
  if(!empty($_GET['do'])) {
    switch (split("/" , $_GET['do'], 2)[0]) {
      case 'radius':
        include('radius.php');
        break;
      case 'tacacs':
        include('tacacs.php');
        break;
      case 'diameter':
        include('diameter.php');
        break;
      case 'kerberos':
        include('kerberos.php');
        break;
      case 'syslog':
        include('syslog.php');
        break;
      case 'network':
        include('network.php');
        break;
      case 'adminer':
echo "
<script type=\"text/javascript\"> location.href = '/adminer.php'; </script>";
        break;
      default:
        include('home.php');
    }
  } else {
    include('home.php');
  }
?>

      <hr>

      <footer>
        <p>&copy; Richard Kuchar 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/jquery/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>
